### ISSUE TITLE
shoulda-matchers and before_validation not compatible?

### ISSUE THREAD

**Issue by findchris** [thoughtbot/shoulda#178]
Hi there.

For context, here is a gist with my Rails model, corresponding spec, and rspec output:
https://gist.github.com/1098642

The issue seems to be caused by the definition of the 'before_validation' callback, as the problem goes away when that line is commented out.

I have been looking into this for a while without much success.  Then again, I'm pretty tired and possibly missing something obvious, in which case I appreciate your second set of eyes.

Is there reason that defining a before_validation callback might cause an issue for shoulda-matchers?  I'm on Rails 3.1.pre.

Thanks,
Chris

**Comment by joshuapinter** [comment]
For others landing here, if you're really interested in testing the presence validation and need to skip a `before_validation` callback, you can use something like this in your model spec: 

```ruby
User.skip_callback( :validation, :before, :assign_secret ) do
  it{ is_expected.to validate_presence_of( :secret ) }
end
```

This will skip that validation and allow you to test presence validation.

**Comment by mcmire** [comment]
@joshuapinter That will change your User model globally thereafter, so I might not advise doing that 😬 If you consider that in your real-world code you will probably never skip the validation, it might not make sense to do that in your tests. Instead, because `secret` is filled in automatically by the model, you might consider removing the presence validation altogether (since it will never fail). Even so, a scenario like this would still be completely testable; you just might not need `shoulda-matchers`. You could say something like:

``` ruby
describe User do
  context 'on creation' do
    context 'when secret is not supplied' do
      it 'fills it in' do
        user = create(:user, secret: nil)
        expect(user.secret).to be
      end

      it 'does not fail a presence validation on :secret' do
        # Note: this will raise an error if this fails validation anyway, so this is kind of
        # redundant, but you could still have it for documentation purposes
        user = create(:user, secret: nil)
        expect(user.errors[:secret]).not_to include("can't be blank")
      end
    end
  end
end
```

**Comment by joshuapinter** [comment]
After testing it a bit more, I noticed that the validate_presence_of in this skip_callback block doesn't even get run. The example is completely skipped by rspec.

I updated my previous comment to thwart others.
