### ISSUE TITLE
shoulda-matchers

### ISSUE THREAD

**Issue by dima4p** [thoughtbot/shoulda#263]
shoulda-matchers latest version is 3.1.2 now. Meanwhile the restriction for the gem is < 3.0. Should not it be updated?

**Comment by sman591** [comment]
This was actually taken care of in #261 over a year ago: https://github.com/thoughtbot/shoulda/pull/261/files#diff-f5c1c460b23bb5ef11e8a4d6c8732e4cR29

Unfortunately it doesn't look like there's been a release since then

**Comment by nickcharlton** [comment]
I've just released `3.6.0` that incorporates that version bump. Thanks for waiting so long!

**Comment by dima4p** [comment]
As my late father used to say, less than one year passed. :-)

**Comment by jasonperrone** [comment]
Well, now matchers is up to 4.1.2. Should we not be using this gem anymore and just put context and matchers in our Gemfile separately?

**Comment by mcmire** [comment]
@jasonperrone Yeah... I think having this meta gem is nice, and this repo has integration tests to ensure the two gems work well together. But you could certainly include them separately, for sure. Note that there are some incompatibilities between the current stable version of shoulda-context and shoulda-matchers right now, although I worked on those issues a while back and put out a preliminary release, 2.0.0.rc2, which you are perfectly free to try out. I haven't really gotten a chance to test out the release, since I don't use shoulda-context, so if everything works for you then maybe I'll just go ahead and make a proper release.
