### ISSUE TITLE
Use transactions to save time setting up context

### ISSUE THREAD

**Issue by wbharding** [thoughtbot/shoulda#272]
Been using and enjoying this gem for 10+ years now, thanks to Thoughtbot for the great work that has gone into it! I'm opening this ticket because I've found that much of our test running time is spent re-running base setup `context` blocks that get reused across nested `should` checks. It _seems_ like it should be possible to adapt `shoulda` so it can store the result of a previously run `setup` as a database transaction. 

I'm considering trying to open a PR that would save the result of `setup` blocks as [savepoints](https://www.postgresql.org/docs/9.1/tutorial-transactions.html) within database transactions, so shoulda could just keep reverting to that transaction state after it runs each `should`, instead of re-running all that context's nested setups for each and every test. 

Before I undertake this effort, I'm curious if this been tried before? I don't see any tickets referencing it. Perhaps it hasn't been attempted because not all databases (e.g., probably not Mysql?) support multiple transaction blocks such that it would be possible to capture the transaction state at various depths of `context`? I'm thinking that an effort to capture `setup` state in a transaction block would probably need to be postgres-specific, at least initially.
 
Any hints as to where such logic would best be placed within this project would be helpful for my potential effort in submitting a PR. Thanks for any assistance.

**Comment by wbharding** [comment]
This looks to be a similar idea implemented for rspec: https://github.com/rosenfeld/rspec_nested_transactions

**Comment by mcmire** [comment]
Hey @wbharding, sorry it took me so long to get back to you on this. That's cool you've used Shoulda for so long!

So there are two things that make me _extremely_ hesitant to add new features like this to Shoulda (and it would really be shoulda-context, since this is just a meta gem, so I'm going to refer to that from now on). The first is that thoughtbot doesn't really use this gem much these days (shoulda-matchers yes, but shoulda-context no). In fact, when I worked there, they'd already [made the decision](https://thoughtbot.com/blog/shoulda-rails3-and-beyond) to switch from Minitest to RSpec 3 years prior. Any maintenance on shoulda-context, then, has only been to make sure that the gem still works with current Ruby/Rails versions and whatnot. The other thing is that since shoulda-context was created, minitest/spec has taken over as the RSpec look-and-feel-alike in the Minitest world. It's been supported way better than shoulda-context has, and, in my opinion, it implements contexts in a more reasonable way than shoulda-context ever will. As a result, modifying minitest/spec to add features like you're describing is a lot easier (there are issues like [adding focus to individual tests](https://github.com/thoughtbot/shoulda-context/issues/52), for instance, which are really difficult to implement in shoulda-context due to how it works — but this already "just works" in minitest/spec).

Anyway, I'm not saying you shouldn't work on this feature. But shoulda-context gets worked on so infrequently that any few functionality would unfortunately create a maintenance burden. For this reason, you would probably have a lot better luck (and control) implementing this feature as a separate gem instead of opening a PR. I know that's not the answer you wanted, but I'm happy to answer any questions you have about the code and help you implement it should you go down this path.

**Comment by wbharding** [comment]
Thanks much for the generous explanation! I'll evaluate some of the newer options you call out.
